### ISSUE TITLE
Keep spoilers on images when they are starred

### ISSUE THREAD

**Issue by Castaras** [CircuitsBots/Starboard#57]
**Is your feature request related to a problem? Please describe.**
If an attached image to a post is spoilered, and then gets starred, the spoiler does not carry over and the image is unspoilered. This causes issues if we have a policy for spoilering images for e.g. film spoilers, pictures of spiders, etc.

**Describe the solution you'd like**
Is there a way to get the image to remain spoilered when embed in the starboard post?

**Additional context**
![image](https://user-images.githubusercontent.com/22918752/103438997-15560700-4c31-11eb-8f6c-d033fa88e9e3.png)

**Comment by CircuitSacul** [comment]
I think the solution is to include the spoilered attachments on the normal message instead of in the embed. It isn't as easy as just sending the message link, because that would mess up the original style. I'll look into a way to do this and let you know if and when I can get it working.

**Comment by Castaras** [comment]
Appreciated! We've been having a mess with using Yag to automatically repost starboard posts with the image spoilered or as a link in the body of the embed field rather than as an attachment, but if you're able to sort this that would be amazing. Let me know if you want any assistance.

**Comment by Castaras** [comment]
something we've discovered is that the entire embed can be spoilered if you spoiler a link to a webpage / image above it in the main text.

**Comment by CircuitSacul** [comment]
Spoilered attachments will now be added above the embed, so they remain spoilered.
