### ISSUE TITLE
Display Starred Messages Using Server Nickname

### ISSUE THREAD

**Issue by pltrant** [CircuitsBots/Starboard#67]
A feature request to display starred messages using the user's server nickname, instead of their Discord username.

**Comment by circuitsacul** [comment]
> A feature request to display starred messages using the user's server nickname, instead of their Discord username.

Once I get the rewrite released (https://github.com/trigondev/starboard) there will be an option to show nicknames instead of usernames.

**Comment by circuitsacul** [comment]
Closing as this has been implemented (`use-server-profile`)
